Update behave (#1545)
behave is installed however it could not run with
error: "Command not found: behave" which can be
seen in this project's integration test jobs:
https://github.com/Sceptre/sceptre/actions/runs/13635718257/job/38113881819

The fix[1] is to update to ver 1.2.6 

[1] https://github.com/behave/behave/issues/310