docs: fix template path in getting-started (#1198)
The default path for templates is already templates directory. This causes `sceptre create` command to fail with  the error message below.
```
FileNotFoundError: [Errno 2] No such file or directory: '.../templates/templates/vpc.yaml'
```