Update behave
behave is installed however it could not run with
error: "Command not found: behave"

This is due to https://github.com/behave/behave/issues/310
and was fixed in version 1.2.6