Update troposphere version
On python 3.10 pip fails when installing troposphere.
The troposphere library needs to be updated to support
python 3.10. It's also pretty old and should be updated
anyways. This is partial resolution for issue #1225

Collecting troposphere<3,>=2.7
  Using cached troposphere-2.7.1.tar.gz (205 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/Users/zaro0508/.pyenv/versions/3.10.1/envs/py310-sceptretest1/lib/python3.10/site-packages/setuptools/__init__.py", line 20, in <module>
          from setuptools.dist import Distribution, Feature
        File "/Users/zaro0508/.pyenv/versions/3.10.1/envs/py310-sceptretest1/lib/python3.10/site-packages/setuptools/dist.py", line 35, in <module>
          from setuptools.depends import Require
        File "/Users/zaro0508/.pyenv/versions/3.10.1/envs/py310-sceptretest1/lib/python3.10/site-packages/setuptools/depends.py", line 7, in <module>
          from .py33compat import Bytecode
        File "/Users/zaro0508/.pyenv/versions/3.10.1/envs/py310-sceptretest1/lib/python3.10/site-packages/setuptools/py33compat.py", line 55, in <module>
          unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
      AttributeError: 'HTMLParser' object has no attribute 'unescape'
      [end of output]