[Resolve #1234] Bugfix in helpers.py
Before this, an empty var file would cause sceptre to fail with an
exception

```
TypeError: 'NoneType' object is not iterable
```

This was caused by yaml.safe_load returning `None` instead of an empty
dict. This adds a default value to avoid this bug.